name: buildkit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+"
    tags:
      - "v*"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "frontend/dockerfile/docs/**"

env:
  SETUP_BUILDX_VERSION: "latest"
  SETUP_BUILDKIT_IMAGE: "registry.internal.huggingface.tech/library/buildkit:latest"
  IMAGE_NAME: "registry.internal.huggingface.tech/library/buildkit"
  PLATFORMS: "linux/amd64"
  DESTDIR: "./bin"

jobs:
  image:
    runs-on:
      group: cpu-high
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: registry.internal.huggingface.tech
      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.event_name == 'pull_request' }}
        id: meta-pr
        uses: docker/metadata-action@v5
        with:
          images: |
            registry.internal.huggingface.tech/library/buildkit
          tags: |
            type=raw,value=sha-${{ env.GITHUB_SHA_SHORT }}
      - name: Build and push Docker image
        run: |
          make images
          docker tag moby/buildkit:local-rootless registry.internal.huggingface.tech/library/buildkit:latest-rootless
          docker push registry.internal.huggingface.tech/library/buildkit:latest-rootless
